### ISSUE TITLE
Chat website

### ISSUE THREAD

**Issue by oAllanWeb** [thekordy/ticketit#175]
hello , I liked the project, would like to know if you have to put a chat module to put on websites.

**Comment by balping** [comment]
Hi @AllanD1 

I'm  not the project maintainer / author and it was a while ago when I last worked on this, because I don't have much time nowadays. So this is only my opinion, it's not me who makes decisions in these type of questions.

There's a [little piece of audio](https://laracasts.simplecast.fm/10), it's less than 7 minutes. I suggest you to listen it.

I absolutely agree with the speaker. I think in this case a chat app just would be too much. If you need one browse the available packages a bit, I'm sure someone has already made something with Laravel. If not, you can also start writing one.

An issue tracking package should be used for issue tracking, a chat app should be used for chatting. If you need both at the same time, then use several packages.

Anyway @thekordy might have a different opinion about this.

**Comment by thekordy** [comment]
I agree with balping .. they are two different channels.
