### ISSUE TITLE
error while including

### ISSUE THREAD

**Issue by dixit-neeraj** [thekordy/ticketit#222]
@thekordy    hello team , 
i wanna use this package in my project. 
i follow same steps as mentioned . 

when i open first time  project-url/tickets-install it open fine but when i submit , it redirects me to
project-url/tickets . 
now it shows me error called $u is undefined .
for more detail check screenshot 
![screenshot from 2016-07-13 15 43 37](https://cloud.githubusercontent.com/assets/8327335/16800115/411161be-4911-11e6-987f-00a009fcaf66.png)

**Comment by thekordy** [comment]
Hi, do you use the users table/model for your auth? and is "id" the primary key for the users?

**Comment by dixit-neeraj** [comment]
yes , it is problem of auth functioniality . 

Now i am facing new issue 
status of ticket does not changed in ticket list after it marked closed/resolved or reopen . 
for super-admin .

**Comment by dixit-neeraj** [comment]
one more issue 
when i create a ticket or simply update it takes a lot of time approx. 2-3 min to things done. 

@thekordy  i hope you have some explanation regarding above 2 issues. 
thanks

**Comment by thekordy** [comment]
> status of ticket does not changed in ticket list after it marked closed/resolved or reopen

Adjust the tickets configuration for the `default_close_status_id` and `default_reopen_status_id`
![ticketi demo - configuration settings 2016-07-17 08-25-01](https://cloud.githubusercontent.com/assets/11343048/16899109/891c2a6a-4c00-11e6-93ec-d3111ad3a00f.png)

> when i create a ticket or simply update it takes a lot of time approx. 2-3 min to things done. 

May be because it sends the email notification, try using the [Laravel Queueing Mail](https://laravel.com/docs/5.2/mail#queueing-mail) and enable it in Ticketit configurations from `Notifications -> queue_emails` setting

**Comment by dixit-neeraj** [comment]
i did the same. 
thanks for answering . :+1:
