### ISSUE TITLE
Datatable does not show my current tickets

### ISSUE THREAD

**Issue by jryd** [thekordy/ticketit#225]
I have followed the install steps and am able to successfully create a ticket, but it then does not show in the datatable on active tickets.

My current "active tickets" count is 4, but the datatable says "No data available in table".

I have included all the yield's:
- `@yield('page')`
- `@yield('content')`
- `@yield('footer')`

There are no errors in my console or anything.

What am I missing?

![active but no show](https://cloud.githubusercontent.com/assets/13251203/16910228/a1432928-4d2b-11e6-9863-742c40e6b97b.PNG)

![footer data table](https://cloud.githubusercontent.com/assets/13251203/16910252/c1ebff24-4d2b-11e6-8765-b31d1675d60f.PNG)

**Comment by jryd** [comment]
OK this related to me having not set a status. However I am now getting an AJAX error on my datatables... The alert on page refers me to https://datatables.net/manual/tech-notes/7

**Comment by jryd** [comment]
This is happening on what appears to be the AJAX call to load the data.
In my network tab it shows: 
`http://localhost/ucp/public/tickets/data?draw=1&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=ticketit.id&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=subject&columns%5B1%5D%5Bname%5D=subject&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=status&columns%5B2%5D%5Bname%5D=ticketit_statuses.name&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=updated_at&columns%5B3%5D%5Bname%5D=ticketit.updated_at&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=agent&columns%5B4%5D%5Bname%5D=users.name&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=priority&columns%5B5%5D%5Bname%5D=ticketit_priorities.name&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=owner&columns%5B6%5D%5Bname%5D=users.name&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=category&columns%5B7%5D%5Bname%5D=ticketit_categories.name&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1468833450986`

and this returns a 500 error for:

> FatalErrorException in Helper.php(99) : eval()'d code line 1:
> Call to a member function diffForHumans() on a non-object

**Comment by marcioquental** [comment]
Same issue here.
I've a fresh install of Laravel 5.2 and this is what I've done until now. I've commented the line on TicketsController that call diffForHumans() function but now I'm facing a different problem. The ajax request comes with 404 not found but if I access the route directly using the browser (eg: /tickets/data) everything looks good, but if I access the route directly with all get params that datatables add to request I've got a 404 not found.
Anyone is facing the same problem? And what is the problem relative with diffForHumans method?

**Comment by thekordy** [comment]
please update to kordy/ticketit:0.2.x-dev or clone 0.2 branch

**Comment by marcioquental** [comment]
Thanks for your response thekordy.
The issue about diffForHumans method is fixed now but I have the same problem with datatables. The request with datatables parameters is getting 404 not found response. Can be something relative with my local environment? I am using vagrant with ubunt 14.04, php version 5.5.30 and I am running the server using the php artisan serve command

EDIT:
I've changed the admin/index.blade.php file to send datatables request via POST instead of GET and now everything is running well. Note that I've need to change the routes file too to send the /data/{id?} via POST and app/Http/Middleware/VerifyCsrffToken.php and add /tickets/data\* to the $except array. This is a dirty solution i know but it is working for now. I dont know if the 404 not found error on datatables request is something relative with my local environment but I will make more tests and post the results here.

**Comment by jryd** [comment]
Updating to kordy/ticketit:0.2.x-dev worked for me.

**Comment by marcioquental** [comment]
Ok, I've tried to load the datatables data on my production server and everything works well.
I think the problem was related with the PHP built in server that I was using on my local environment and I think there is a problem relative with the request URI length. So, for those who have the same problem try running the application using a web server.

**Comment by ghost** [comment]
> 
> 
> Updating to kordy/ticketit:0.2.x-dev worked for me.

while updating, what you type Token?
