### ISSUE TITLE
How to customise emails

### ISSUE THREAD

**Issue by sunnyjayjay** [thekordy/ticketit#249]
Have you got any guide or instructions on how to customise the emails please?

**Comment by aenciso** [comment]
All emails are under resources/views/vendor/ticketit/emails/*_/_.php

If you don't have that you need to run 

php artisan vendor:publish

to copy all customisable files to your project folder

**Comment by sunnyjayjay** [comment]
I understand that completely and have already made some mods in those files. But it is not clear at all. What are the variables passed to the templates? Where and when and how are they passed? Can we add more variables of our own? If so, how? Can we have some emails fire and others not? This is a very important but less intuitive part of your app and yet there is no instruction for it in your Wiki.

**Comment by thekordy** [comment]
@sunnyjayjay see #234 .. if you need to customize this behaviour and counters (as your question #250) .. you can copy the `TicketitServiceProvider` to your `app/providers` directory .. change the name space .. add the new service provider to `config/app.php` providers instead of the `Kordy\Ticketit\TicketitServiceProvider::class`
