### ISSUE TITLE
Laravel 5.3

### ISSUE THREAD

**Issue by sunnyjayjay** [thekordy/ticketit#293]
I am reopening this issue because it is not resolved. I have Ticketit working great in a Laravel 5.2 app. However I cannot get it to work in a 5.3 app. Php artisan always gives an error and it seems the error is a non-object in Settings.php at line 57 or 58. Is there something different I have to do for 5.3?

I have cleared the cache, cleared compiled, dumped autoload. No difference. Points always to an error in Ticketit Settings.php.

**Comment by balping** [comment]
I closed the other one because it looked the same issue as https://github.com/thekordy/ticketit/issues/288 It's better to have everything related in one thread. Might not be the same though

1. check if you have version >=0.3 installed
2. check if you've got a  route row in the settings table in the db
3. A detailed error message would be useful

**Comment by sunnyjayjay** [comment]
What do you mean by "a route roe" in the settings table?

I have now finally got this working locally but I still cannot get it to work on Forge. 

    `php artisan clear-compiled `

gives that Settings.php error at line 57.

**Comment by thekordy** [comment]
I think he means routes row as he mentioned in the linked issue #288 

> Other idea: check your database, you should have a row in the settings table, with slug routes. If you don't have that add it. The value should be

**Comment by balping** [comment]
Yes, exactly. Just check 

```sql
SELECT * from ticketit_settings where slug = 'routes'
```
