### ISSUE TITLE
Tickets not been displayed

### ISSUE THREAD

**Issue by sekhoanem** [thekordy/ticketit#299]
![tickets](https://cloud.githubusercontent.com/assets/21284746/22965013/1c6b3f4e-f364-11e6-8500-620a1933eb94.jpg)

I have installed the packages successfully and everything runs smoothly but the only issue is that the tickets do not display. The counter bubble just increments to indicate number of tickets by the tickets cant be viewed. Whats the reason for this? And how can I alter the css so that some menu links appear?

I have tried to add: @yield('footer') but the problem is still there....when I type: http://localhost:8000/tickets/4 the ticket with all its details can be viewed. I am confused.

**Comment by sekhoanem** [comment]
![te](https://cloud.githubusercontent.com/assets/21284746/22966837/9b461016-f36c-11e6-9fd5-3df25d621520.jpg)

**Comment by thekordy** [comment]
you might have same issue as here #205

**Comment by sekhoanem** [comment]
Thanks that helped me but now a new datatables problem....see pics below

**Comment by sekhoanem** [comment]
![1](https://cloud.githubusercontent.com/assets/21284746/22970554/4092083c-f37b-11e6-8a5c-86946c3fc020.jpg)
![2](https://cloud.githubusercontent.com/assets/21284746/22970557/42da351a-f37b-11e6-82a1-3b6f1b4f1146.jpg)

**Comment by thekordy** [comment]
Have you created at least one status, priority, and category?

https://github.com/thekordy/ticketit/issues/284#issuecomment-270969003

**Comment by sekhoanem** [comment]
yes....I have...The tickets now appear but first the datatable error pops up

**Comment by thekordy** [comment]
Please search our closed issues, I think we solved this before.

**Comment by spaceSquid** [comment]
No link to fix?

**Comment by FlaseSb** [comment]
our closed issues?where

**Comment by balping** [comment]
https://github.com/thekordy/ticketit/issues?q=not%20displayed

**Comment by GelLiNN** [comment]
I have created the status, priority, category, and verified my yields are in the correct places.  But I still have this exact same issue.

![screenshot from 2018-07-12 15-41-36](https://user-images.githubusercontent.com/11727088/42663378-2261453c-85ea-11e8-8a67-536e02bd6dba.png)

I was thinking this could be a cache problem, but in the inspector it seems to pick up my script references just fine.  Strange that I'm getting the datatables js error (see console), I havent seen anyone else get that error with ticketit.

UPDATE:  I have fixed the datatables console error by using a cdn version of jquery instead of my own local copy, but the tickets are still not being displayed.  If I go into my network tab, the request for the data going in the table is coming back with results, and visiting tickets/data displays all the tickets data just fine.

![screenshot from 2018-07-12 17-01-17](https://user-images.githubusercontent.com/11727088/42665629-57e04a68-85f5-11e8-8269-a0bdd665aacc.png)

What is going on here?  Why won't the tickets display?

Thanks!

**Comment by balping** [comment]
Interesting. Is jquery executed before datatables (ie no async or defer)?

**Comment by GelLiNN** [comment]
Yeah as you can see in the picture the script link to the CDN for JQuery is before the datables script.  Thanks for the response!  I can also send an ngrok link to my build if you want to take a look at what Im dealing with.

Thanks again Balping

**Comment by balping** [comment]
@GelLiNN OK, we can give it a try.

**Comment by GelLiNN** [comment]
http://***.ngrok.io
You can log in as ***
pass: ***

But watch out you may get too many requests error, just wait a minute if that happens.
I noticed that using php artisan serve and then ngrok for tunneling the tickets are showing up now.

My default way to run the server is through xampp, without artisan serve.  any idea why this would be preventing datatables from loading the tickets in the list?

**Comment by balping** [comment]
Yes, I could log in and see that it's working.

Yes, if you used `artisan serve` previously that explains why it didn't work. It's a [known bug](https://github.com/yajra/laravel-datatables/issues/497#issuecomment-205602652), that I forgot about. Use `php -S localhost:8000 -t public` instead and that'll do the job.

----
UPDATE 


Sorry, I misunderstood. I haven't used xammp, so I can't tell you anything about it. But `php -S localhost:8000 -t public` should work for sure.

**Comment by GelLiNN** [comment]
I'm going to need it to run through the LAMP server for when I go live for production.  But it is good to know this works for testing purposes.  It makes no sense to me why it would work hosting it one way but not the other..?

**Comment by balping** [comment]
OK, just realised that xampp is basically apache. It has always worked for me with apache. Sorry, I've got no clue, what can be wrong.

**Comment by GelLiNN** [comment]
Maybe thekordy would have some idea?

**Comment by balping** [comment]
I think you might get luckier if you tried to get help directly at datatables: https://github.com/yajra/laravel-datatables/issues
