### ISSUE TITLE
Branches :)

### ISSUE THREAD

**Issue by fusiondesign** [thekordy/ticketit#324]
Can anyone explain our branches and any new strategies I should be caught up on? The naming seems a bit off.

I'm just getting back into things with a new job and having moved across state!

**Comment by balping** [comment]
0.1 unused
0.2 current stable - bugfixes, compatibility fixes (with new laravel versions) and new translations only. At least this has been the convention. I don't know if @thekordy wants to break it or not, since a couple of new PRs are open wanting to add completely new features. (And yes, current stable release is 0.3.x, but it is still the 0.2 branch... :-) )
1.0 dead
2.1 for new version, being rewritten from zero, but not much work has been done in the last few months. 2.0 and 2.1 were split to handle different versions of laravel, but newest Laravel versions are far ahead, I don't think this split is relevant in any sense by now. I think new code should be written for 5.5 which will be the next LTS

So if you want to help and make progress, use the 2.1 branch to implement features listed in some issue still open here. (Assuming L 5.5 environment)

**Comment by balping** [comment]
Yep, read through this: https://github.com/thekordy/ticketit/issues/184

**Comment by fusiondesign** [comment]
Perfect! Exactly the info I needed :+1: thanks @balping !!

**Comment by thekordy** [comment]
@FusionDesign long time not seen dude, welcome back :)

as @balping said, that was the plan, recently I am thinking the new version should focus on L5.5 (may be L5.4) and let 5.3- to 0.2 (which became 0.3 now :D) .. So Ticketit 2.5 (or 2.4) might be the right target.
