### ISSUE TITLE
Hi, How can I install this package if my user table split name field to first_name and last_name?

### ISSUE THREAD

**Issue by angelkurten** [thekordy/ticketit#406]
Hi, How can I install this package if my user table split name field to first_name and last_name?

**Comment by balping** [comment]
Just define an [accessor](https://laravel.com/docs/5.5/eloquent-mutators#defining-an-accessor) on your user model:

```php
public function getNameAttribute(){
    return "{$this->first_name} {$this->last_name}";
}
```

**Comment by sarkkk** [comment]
I have 'fullname' column instead of 'name' and using following code as accessor on my UserModel. 

```
<?php

namespace Modules\Users\Entities;

use Illuminate\Database\Eloquent\Model;

class UserModel extends Model
{
	
    
    protected $guarded = ['id', 'created_at', 'udpated_at'];

    protected $table = 'users';

    public function userdocs() {
		return $this->hasMany(Module\Userdocument\Entities\Userdoc);
	}
	  
	public function getNameAttribute(){
    return "{$this->fullname}";
}


}


```
but still getting this error 
Column not found: 1054 Unknown column 'name' in 'field list' (SQL: select `name`, `id` from `per_users`)

**Comment by balping** [comment]
OK, then it's not as easy as I thought.

Two possible solutions I can imagine (neither of them is very nice):

a) Duplicate columns

Add a `name` field to the users table. Then use a [mutator](https://laravel.com/docs/5.5/eloquent-mutators#defining-a-mutator) to update `name` when you update `fullname`:

```php
 public function setFullNameAttribute($value) {
    $this->attributes['fullname'] = $value;
    $this->attributes['name'] = $value;
}
```

b) Use views

Ticketit requires `\App\User`. Create another user model that you use elsewhere in your project, and reserve `\App\User` only for Ticketit. In your other model you can do whatever you want. But for `\App\User`, create an SQL view, that aliases `fullname` to `name`, like this:

```SQL
CREATE VIEW `ticketit_users` AS SELECT *, `fullname` AS `name` FROM `users`;
```

Then in your `\App\User` model set table to `ticketit_users`:

```php
namespace App;

class User extends Model
{
    protected $table = 'ticketit_users';
}
```

Then in `\App\User`, ticketit will have access to a `name` column. But since it's through a view, you cannot modify it, that's why you need another model with the real table behind.

**Comment by sarkkk** [comment]
Thank you balping for quick response, I renamed column `fullname` to `name` and succeed to get the installation page.

After clicking proceed button another error occurred, i am getting this error:


> (1/1) FatalErrorException
Maximum execution time of 300 seconds exceeded
> --
> in OutputFormatter.php (line 137)
> 
>
