### ISSUE TITLE
Add new Form at "Create New Ticket"

### ISSUE THREAD

**Issue by kelilipan** [thekordy/ticketit#454]
Hello,
i want to add new form at Create New Ticket like "your email" "Phone" or something else.
what should i do ?

**Comment by balping** [comment]
1. Publish views so you can edit the html layout of the form: `php artisan vendor:publish`

2. Create a migration that extends the table `ticketit` with fields you want.

3. Override `TicketsController` so that in the store method you can add the functionality to store extra fields. This is how to override  a vendor class (read the comments too): https://stackoverflow.com/a/34600074

**Comment by anto1399** [comment]
@balping I do not seems to understand the key/path provided by the link in point 3. Could you please be explicitly on how to do that? 
For instance I want to copy the TicketsController from vendor/kordy/ticketit to app/Http/Controllers so as to override the store method. How should I link it in the composer.json file?

**Comment by balping** [comment]
I would separate to an overrides directory

Try this:

```
 "autoload": {
     "files": ["overrides/TicketsController.php"],
     "exclude-from-classmap": ["vendor/kordy/ticketit/Controllers/TicketsController.php"]
  }
```

**Comment by anto1399** [comment]
Thanks very much @balping. The action is now hitting the store method in the overrides/TicketsController.php instead of the vendor file.
