### ISSUE TITLE
Ticket assignment question

### ISSUE THREAD

**Issue by antvet** [thekordy/ticketit#473]
I didn't get it... How does ticket assignment work? Which agent will be placed first?
Is it possible to assign the ticket to no one by default and allow all agents to see unassigned tickets?

Thanks in advance

(edit: grammar)

**Comment by balping** [comment]
If in doubt, check the source. (This is a general advice for any free software.)This piece of code is responsible for auto assignment:

https://github.com/thekordy/ticketit/blob/8114048bd882b7577998b54299d67d4f7b33ec79/src/Models/Ticket.php#L196-L222

So basically it is assigned to the one with lowest number of open tickets, if no agent is found then it's assigned to admin. (Now by looking at it, I can see that this implementation is probably not efficient, might need a refactor.)

What you ask for is currently not possible, but since this is free software, you are free to change the code and fit it for your needs.

**Comment by antvet** [comment]
Thank you for your answer @balping. Just a last question in the same subject: I saw in _Configuration_ > _Settings_ that we can add custom settings. Is it possible to assign every incoming tickets to the same agent, then?

EDIT: Okay, it was really easy. I just removed the code from line 207 to line 219 of the file you linked above.
