### ISSUE TITLE
The "../resources/views/" directory does not exist.

### ISSUE THREAD

**Issue by rylxes** [thekordy/ticketit#476]
When i go to the url http://{{domain}}/tickets-install ,  

i think the issue is with the line of code : `$this->viewsFilesList('../resources/views/')` 
in InstallController  line 51

Laravel Version :  5.6

**Comment by rylxes** [comment]
... another note, ... is there a reason `base_path()` is not used in that line so it would look like `base_path()."/resources/views/"`

**Comment by balping** [comment]
Hi!

Thanks for pointing this out. Others have had the same issue before (#453 #465), but I thought it was caused by something else. I couldn't replicate the bug, however your suggestion of using an absolute path might solve the issue.

Please see if this commit  solves your problem: a889476\
If it does, I'll release it soon.

**Comment by rylxes** [comment]
thats awesome , ... it solved the problem 

Cheers

**Comment by balping** [comment]
Fix released
