### ISSUE TITLE
Localisation needed

### ISSUE THREAD

**Issue by balping** [thekordy/ticketit#5]
Just as in title. Of course, I can edit views, but changes made under `resources/views/vendor/kordy/ticketit/` have no effect since the views are loaded from the source directory. And I wouldn't like to edit them because I'm hoping for updates + the `vendor` folder is excluded from the git repository and I won't change it.

Great project, great start anyway. Just needs some polishing

**Comment by thekordy** [comment]
I am planing to implement the localization, I may consider to give it higher priority now.

But as a side note, you may customize as follow:

publish views to the path resources/views/vendor/kordy/ticketit using this artisan command

```shell
	php artisan vendor:publish --provider="Kordy\Ticketit\TicketitServiceProvider" --tag="views"
```

Then go and edit the package views at resources/views/vendor/kordy/ticketit and customized views will override the package original views

**Comment by balping** [comment]
That's what I tried, but they weren't overridden. I'll try it again tomorrow.

**Comment by balping** [comment]
Oh sorry, you have already fixed that

**Comment by FusionDesign** [comment]
Updated ticketit.fusiondesign.me with new users and latest version (old version of ticketit.fusiondesign.me was using a custom package due to the PSR-4 problems prior to 0.5 IIRC). Switched live demo to stock install and it looks epic. Can't wait to get my hands dirty now that my site is on Bootstrap and I'm finally over the PSR-4 hump with packages :)
