### ISSUE TITLE
Multi tenancy

### ISSUE THREAD

**Issue by MichaelGhattas** [thekordy/ticketit#500]
Hey, why don't you support tickets per client (admin) .. any ideas how we can support that ?

**Comment by balping** [comment]
What do you mean by this?

**Comment by MichaelGhattas** [comment]
Thanks for the quick response. 

I want to have multiple admins (clients) creating tickets that are only visible to them. 
Right now, all tickets belong to one admin. I hope that clarifies what I'm trying to achieve.

**Comment by balping** [comment]
Just to clarify terminology: there are agents in the system who can be assigned to different categories; there are admins who can access every ticket and there are plain users who can access their own tickets only. Still not sure what you want, sorry.

**Comment by MichaelGhattas** [comment]
Sorry for lack of clarity. I want to implement this package on a multi-tenant solution. Hence, I want 10 different clients to use the ticketing system without accessing each other's tickets. Hope this clarifies it.

**Comment by balping** [comment]
OK, now it's clear. I think you should use a proper multi-tenant package such as [hyn](https://laravel-tenancy.com/). This guarantees separated data. Shouldn't be too difficult to set up with ticketit. The only drawback is that you'll need to configure ticketeit for each tenant. But since you can  can copy the config table with sql dumps, this shouldn't be too time-consuming either. No plans for supporting multi-tenancy inside this package though.
