### ISSUE TITLE
Route Not Found

### ISSUE THREAD

**Issue by jim1506** [thekordy/ticketit#521]
I used you quick installer and made all the appropriate changes in your notes including seeding. I decided to add a user (me) and grant admin access by setting the flag in the users table.

So I started by selecting register and then filled in the form, but I got:

> Action Kordy\Ticketit\Controllers\TicketsController@index not defined.

I have checked that the App URL is correct in config/app

**Comment by balping** [comment]
When running the quick installer, it creates you an admin user; can you log in with that one?

Also, when using the quick installer the only command you need to run is `php artisan ticketit:install`. Since you say that you also ran the seeder manually and made other changes, makes me think that you haven't followed the quick installer method properly. 

You could also check the row `slug='routes'` in table `ticketit_settings` to see if it points to an existing file.
