### ISSUE TITLE
Carbon Values are not translated

### ISSUE THREAD

**Issue by datune** [thekordy/ticketit#87]
You are using diffForHumans, which produces output such as "20 seconds ago", but these values are not translated...

I did a bit of research and I think it can be fixed by using this: https://github.com/jenssegers/date

**Comment by datune** [comment]
I'm going to make a pull request showing how to fix this...

**Comment by datune** [comment]
Alright, my second pull request incorporates this "fix/feature". 

Basically, here are the steps: 
- Add requirement to composer.json
- Override two methods in Model Ticket.php (freshTimestamp() and asDateTime())
- Add bindings to register method in TicketitServiceProvider

**Comment by thekordy** [comment]
Thank you very much for your both PR, I tested them and I found no problems, well done.

One thing, in order to allow people to use the jenssegers package without errors, we need them to upgrade using the composer, the most easy way is to make a new patch, that's why I created a new 0.2.1 branch.
So if it is possible, would you please make the PR to the 0.2.1 branch instead of the 0.2 ?

**Comment by thekordy** [comment]
Applied your Fix to v0.2.1 .. Thank you very much

**Comment by datune** [comment]
Thanks, sorry I did not have the time to apply it to 0.2.1...

**Comment by thekordy** [comment]
Never mind, and Thank you again for your contributions, it made Ticketit better :+1:
